---
- name: Install required packages
  yum:
    name:
      - ctdb
      - samba
    state: latest
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Make sure lock folder is present
  file:
    path: /gluster/lock
    recurse: yes
    state: directory
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Mount ctdb volume
  mount:
    src: "{{ item }}:/{{ glusterfs_ctdb_config_volume }}"
    path: /gluster/lock
    fstype: glusterfs
    state: mounted
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Copy ctdb config file
  copy:
    src: ctdb
    dest: /gluster/lock
  notify:
    - restart ctdb

- name: Copy templates files
  template:
    src: "{{ item }}.j2"
    dest: "/gluster/lock/{{ item }}"
  with_items:
    - public_addresses
    - nodes
  notify:
    - restart ctdb

- name: Create symlinks
  file:
    src: "/gluster/lock/ctdb"
    dest: "/etc/sysconfig/ctdb"
    force: yes
    state: link
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Create symlinks
  file:
    src: "/gluster/lock/public_addresses"
    dest: "/etc/ctdb/public_addresses"
    force: yes
    state: link
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Create symlinks
  file:
    src: "/gluster/lock/nodes"
    dest: "/etc/ctdb/nodes"
    force: yes
    state: link
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Make sure shares folder is present
  file:
    path: /gluster/shares
    recurse: yes
    state: directory
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Mount glusterfs volume that will host shares
  mount:
    src: "{{ item }}:/{{ glusterfs_ctdb_shares_volume }}"
    path: /gluster/shares
    fstype: glusterfs
    state: mounted
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb

- name: Create shares folders
  file:
    path: "/gluster/shares/{{ item.name }}"
    state: directory
    recurse: yes
    owner: "{{ item.force_user | default('nobody') }}"
    group: "{{ item.force_group | default('nobody') }}"
  with_items:
    - "{{ glusterfs_ctdb_shares }}"
  notify:
    - restart ctdb

- name: Deploy shares configuration
  template:
    src: smb_shares.conf.j2
    dest: "{{ glusterfs_ctdb_samba_shares_config_path }}"
  delegate_to: "{{ item }}"
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  notify:
    - restart ctdb
