---
- name: Executing only on CentOS 7 if glusterfs_role_master is set to true
  block:
  - include_tasks: install.yml
  - include_tasks: replica-volumes.yml
  - include_tasks: geo-replication.yml
    tags:
      - glusters_geo_replication
  when: 
    - ansible_distribution + ansible_distribution_major_version == "CentOS7"
    - glusterfs_role_master == true
