---
- name: Executing only on CentOS 7 if glusterfs_master is set to true
  block:
  - include_tasks: install.yml
  - include_tasks: gluster.yml
  when: 
    - ansible_distribution + ansible_distribution_major_version == "CentOS7"
    - glusterfs_master == true
