---
- name: Join cluster members
  shell: "gluster peer probe {{ item }}"
  register: gluster_peering
  changed_when: "'already in peer list' not in gluster_peering.stdout"
  with_items:
    - "{{ glusterfs_cluster_members }}"
  tags:
    - glusterfs
    - glusterfs_replica_volumes

- name: Create the replicas volumes
  gluster_volume:
    state: present
    name: "{{ item.name }}"
    bricks: "{{ item.bricks }}"
    cluster: "{{ item.cluster | default([inventory_hostname] | list + glusterfs_cluster_members) }}"
    replicas: "{{ item.cluster | default([inventory_hostname] | list + glusterfs_cluster_members) | length }}"
    force: yes
  with_items:
    - "{{ glusterfs_replica_volumes }}"
  tags:
    - glusterfs
    - glusterfs_replica_volumes

- name: Start the replica volumes
  gluster_volume:
    state: started
    name: "{{ item.name }}"
  with_items:
    - "{{ glusterfs_replica_volumes }}"
  tags:
    - glusterfs
    - glusterfs_replica_volumes
