---
- name: restart glusterd
  systemd:
    name: glusterd
    enabled: yes
    state: restarted
  with_items:
    - "{{ inventory_hostname }}"
    - "{{ glusterfs_cluster_members }}"
  delegate_to: "{{ item }}"
